New-Item -ItemType Directory -Force -Path "Context/2025-11-21/subs" | Out-Null
Push-Location "Context/2025-11-21/subs"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "01_%(id)s.%(ext)s" "https://youtu.be/4SWEpdg81y0?si=f4f-Myy7oUDwNui-"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "02_%(id)s.%(ext)s" "https://youtu.be/9xzxc-8rFno?si=aV8-r0TLmeqITiyg"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "03_%(id)s.%(ext)s" "https://youtu.be/MyHnIREZg4k?si=mRLj0CA2wd1TkL2S"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "04_%(id)s.%(ext)s" "https://youtu.be/n-DUKAXq3tg?si=ovbYdgpx0qfNCpZ3"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "05_%(id)s.%(ext)s" "https://youtu.be/edTFSnznfoA?si=YPgib7oFZUBIx6-Q"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "06_%(id)s.%(ext)s" "https://youtu.be/a7vTTbREb3A?si=4MzZmJFFrx8yK5k3"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "07_%(id)s.%(ext)s" "https://youtu.be/4XF_mOxCN3k?si=qYQSIUx-Bc10W2it"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "08_%(id)s.%(ext)s" "https://youtu.be/2KtWzHtbinc?si=sC_pFbvvq8hI9sEu"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "09_%(id)s.%(ext)s" "https://youtu.be/Y6BnbEFnPuQ?si=MzJ__1ClCnhAKD_I"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "10_%(id)s.%(ext)s" "https://youtu.be/46bGG6bTZZs?si=oI65l4jcrvH8TYI5"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "11_%(id)s.%(ext)s" "https://youtu.be/Hnoe8hNPFr8?si=FRHc6lN47br5kptj"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "12_%(id)s.%(ext)s" "https://youtu.be/ouc6iX4dlMw?si=dvQJagmyG_W872I5"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "13_%(id)s.%(ext)s" "https://youtu.be/T6WEBTp8Hk0?si=gFS9cRmm6ajPEAM_"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "14_%(id)s.%(ext)s" "https://www.youtube.com/watch?v=9Uc62CuQjc4&list=PLUPEBWbAHUsyiuhVHPbzQbalNYfItnxKq"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "15_%(id)s.%(ext)s" "https://youtu.be/74Pn1L23LXE?si=EFCcrYjcf8k3ZAKd"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "16_%(id)s.%(ext)s" "https://youtu.be/ShX_4i1ncVM?si=tJwqaaeEt6ORFhbj"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "17_%(id)s.%(ext)s" "https://www.youtube.com/watch?v=ppRgvfIJsgU"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "18_%(id)s.%(ext)s" "https://www.youtube.com/watch?v=P9ApmHdPZeI"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "19_%(id)s.%(ext)s" "https://youtu.be/NQ8UJbhQZB8?si=Nlyvt13JYH_T45Gw"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "20_%(id)s.%(ext)s" "https://www.youtube.com/watch?v=k9BeLSHBNlI"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "21_%(id)s.%(ext)s" "https://www.youtube.com/watch?v=hkzV24Hmj_A"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "22_%(id)s.%(ext)s" "https://youtu.be/eIVjK1OgWTg?si=OfpY1Zd0pmvvUjjg"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "23_%(id)s.%(ext)s" "https://youtu.be/M4OVyK7YgK0?si=HP-I4rJZBWE8WjoA"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "24_%(id)s.%(ext)s" "https://www.youtube.com/watch?v=YCOtQU4jyPw"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "25_%(id)s.%(ext)s" "https://youtu.be/7pWc-a5shRk?si=UDxgLOk2Lro67WCl"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "26_%(id)s.%(ext)s" "https://youtu.be/cDsOARyWB3c?si=hhauGM4ESFqxtbyD"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "27_%(id)s.%(ext)s" "https://youtu.be/h8DJS1LtYO4?si=hch6CPm--oZu_YZG"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "28_%(id)s.%(ext)s" "https://youtu.be/QXtsEPsAQ8k?si=5ZYZGzmShEuuA-gR"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "29_%(id)s.%(ext)s" "https://youtu.be/vN8I1iAUZcY?si=jkVW78HmfBR7HSgv"
yt-dlp --no-playlist --socket-timeout 30 --retries 5 --ignore-errors --no-warnings --write-auto-subs --sub-lang en --skip-download -o "30_%(id)s.%(ext)s" "https://youtu.be/MGRuqYiaWog?si=8aaE1HmKk3qi3HMq"
Pop-Location